# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  akhwebshop:
    image: akhwebshop
    build:
      context: .
      dockerfile: backend/AKHWebshop/AKHWebshop/Dockerfile
    ports:
      - 5000

  database:
    image: mysql:8.0
    ports:
      - 3306
    env_file:
      - ./database/.env

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/out:/data/frontend
